### ISSUE TITLE
Handkarten gib/entferne alle Handkarten 

### ISSUE THREAD

**Issue by fablucius** [thiessena/MinuteDungeon#10]
Hallo Luca, kannst du bitte diese zwei Methoden für die Klasse Handkarten programmieren: 

1. List <Karte> gibAlle(), die alle Handkarten zurückgibt
2. void entferneAlle(), die alle Handkarten entfernt 
Danke <3

**Comment by Leeee11** [comment]
Hallo Luca,

Ich werde der Sache nachgehen und im winden und schwindes Eile die benötigt und angeforderten Methoden hinzufügen um deine kostbare und hiermit wertgeschätze Zeit nicht länger zu erweitern. 

Bis dahin <3   \( ;-;)/

**Comment by thiessena** [comment]
Hallo luca, 
habe beide Methoden implementiert.
